-- |
-- Module: Zap.Gen
-- Description: Code generated by the schema compiler.
--
-- The @Zap.Gen@ module hierarchy contains code generated by the schema compiler.
-- See "Zap.Tutorial" for a description of what code is generated for
-- each schema, as well as a general introduction to the library.
module Zap.Gen () where
